name: Cleanup devcontainer images

on:
  schedule:
    - cron: "0 3 * * 0" # 毎週日曜日
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        package:
          - devcontainers/base
          - devcontainers/go
          - devcontainers/rust
          - devcontainers/java
          - devcontainers/swift
      fail-fast: false

    steps:
      - name: Delete old untagged versions of ${{ matrix.package }}
        uses: actions/delete-package-versions@v5
        with:
          package-name: devcontainers/${{ matrix.package }}
          package-type: "container"
          min-versions-to-keep: 0 # タグなしは全削除
          delete-only-untagged-versions: "true"
        continue-on-error: true

      - name: Keep latest 3 tagged versions of ${{ matrix.package }}
        uses: actions/delete-package-versions@v5
        with:
          package-name: devcontainers/${{ matrix.package }}
          package-type: "container"
          min-versions-to-keep: 3 # タグ付きは最新3つ保持
        continue-on-error: true
